name: build

on:
  pull_request:
    branches: [main, master]
  push:
    branches-ignore: [main, master]
  workflow_call:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  build:
    uses: SpiralP/github-reusable-workflows/.github/workflows/build.yml@7e0f2e3759bc2b0576a8921dfa33fb449d5e8a1b # main
