name: build

on:
  pull_request:
    branches: [main, master]
  push:
    branches-ignore: [main, master]
  workflow_call:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  build:
    uses: SpiralP/github-reusable-workflows/.github/workflows/build.yml@16b82b3992f607ddfc9cf5d222c1d482d5db4940 # main
