name: build

on:
  pull_request:
    branches: [main, master]
  push:
    branches-ignore: [main, master]
  workflow_call:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  build:
    uses: SpiralP/github-reusable-workflows/.github/workflows/build.yml@2d4d6b3a7adfb72d73b749efcec0f96a1a528bad # main
