name: Update lock files

on:
  schedule:
    - cron: "0 0 1 * *" # monthly
  workflow_dispatch:

concurrency:
  group: update-lock-files-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update_nix_hashes:
    uses: SpiralP/github-reusable-workflows/.github/workflows/update-lock-files.yml@main
    with:
      npm-attribute: default
      rust-attribute: wasm
